CREATE TABLE IF NOT EXISTS disks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    disk_name TEXT NOT NULL,
    disk_number INTEGER NOT NULL DEFAULT 0,
    source_path TEXT NOT NULL COLLATE NOCASE UNIQUE,
    volume_label TEXT NOT NULL DEFAULT '',
    total_capacity INTEGER NOT NULL DEFAULT 0,
    free_space INTEGER NOT NULL DEFAULT 0,
    cluster_size INTEGER NOT NULL DEFAULT 0,
    serial_number TEXT NOT NULL DEFAULT '',
    file_system TEXT NOT NULL DEFAULT '',
    total_files INTEGER NOT NULL DEFAULT 0,
    total_folders INTEGER NOT NULL DEFAULT 0,
    added_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT '',
    disk_type TEXT NOT NULL CHECK (disk_type IN ('CD', 'DVD', 'BluRay', 'HardDisk', 'SolidStateDisk', 'RemovableUSB', 'VirtualDisk', 'Other'))
);
